from agents.skill import Skill
from pydantic import BaseModel


distill_system_prompt = """
You receive python code written to control a robotic arm in a simulated environment.
You will receive a number of related or similar functions, and your goal is to refine these, with the ultimate goal of making them more reusable for future code generations.
These functions may:
- use similar subroutines, which you could extract into a new function.
- be overly specific, where they could be generalised
- contain assumptions that are not appropriately modelled as function arguments
- be poorly named
- fulfil the same function, s.t. that some can be subsumed by a single more general function
- ...
Concretely, you should propose revisions to the given set of functions, which will then be realised in later LLM calls.

Try to reduce the total number of functions as far as possible, i.e. try to make each revised function as powerful and meaningful as possible, and don't generate more revisions than necessary.

It is crucial that the revised code will lead to the SAME outputs as the previous codes, as this is how we test your revisions.
"""


def distill_prompt(skills: list[Skill]):
    return f"""
    The skills you are supposed to revise are: 
    {"\n---------------------------\n".join([skill.code for skill in skills])}
    """


extract_insights_system_prompt = f"""
A robotic arm is controlled by writing python code using a simple API. 
Tasks mostly involve placing different sorts of blocks on top of one another in interesting ways.
Attempts at solving the task are generated by an AI agent, and a human assesses the task success and provides feedback.
This feedback will often contain some insights, that will be useful in the future as well. 
Your role is to extract insights from this feedback.

Provide only the insight gained from the last round of feedback in your response, be concise. 
There might be no insights to extract.
"""


def extract_insights_prompt(task, code_attempt, feedback):
    return f"""
    The task was {task}.
    The agent attempted to solve it using the following code: {code_attempt}.
    The feedback provided by the human was: {feedback}.
    """
