cfg_tabletop = {
    'lmps': {
        'tabletop_ui': {
            'prompt_text': open(f"prompts/main_prompt.txt").read(),
            'temperature': 0,
            'query_prefix': '# ',
            'query_suffix': '.',
            'stop': ['#', 'objects = ['],
            'maintain_session': True,
            'debug_mode': False,
            'include_context': True,
            'has_return': True,
            'return_val_name': 'whole_answer',
        },
        # 'parse_obj_name': {
        #     'prompt_text': open(f"prompts/capravens/prompt_parse_obj_name.txt").read(),
        #     'temperature': 0,
        #     'query_prefix': '# ',
        #     'query_suffix': '.',
        #     'stop': ['#', 'objects = ['],
        #     'maintain_session': False,
        #     'debug_mode': False,
        #     'include_context': True,
        #     'has_return': True,
        #     'return_val_name': 'ret_val',
        # },
        # 'parse_position': {
        #     'prompt_text': open(f"prompts/capravens/prompt_parse_position.txt").read(),
        #     'temperature': 0,
        #     'query_prefix': '# ',
        #     'query_suffix': '.',
        #     'stop': ['#'],
        #     'maintain_session': False,
        #     'debug_mode': False,
        #     'include_context': True,
        #     'has_return': True,
        #     'return_val_name': 'ret_val',
        # },
        # 'parse_question': {
        #     'prompt_text': open(f"prompts/capravens/prompt_parse_question.txt").read(),
        #     'temperature': 0,
        #     'query_prefix': '# ',
        #     'query_suffix': '.',
        #     'stop': ['#', 'objects = ['],
        #     'maintain_session': False,
        #     'debug_mode': False,
        #     'include_context': True,
        #     'has_return': True,
        #     'return_val_name': 'ret_val',
        # },
        # 'transform_shape_pts': {
        #     'prompt_text': open(f"prompts/capravens/prompt_transform_shape_pts.txt").read(),
        #     'temperature': 0,
        #     'query_prefix': '# ',
        #     'query_suffix': '.',
        #     'stop': ['#'],
        #     'maintain_session': False,
        #     'debug_mode': False,
        #     'include_context': True,
        #     'has_return': True,
        #     'return_val_name': 'new_shape_pts',
        # },
        'fgen': {
            'prompt_text': open(f"prompts/fgen.txt").read(),
            'temperature': 0,
            'query_prefix': '# define function: ',
            'query_suffix': '.',
            'stop': ['# define', '# example'],
            'maintain_session': False,
            'debug_mode': False,
            'include_context': True,
        },
        # 'parse_completion': {
        #     'prompt_text': open(f"prompts/capravens/prompt_parse_completion.txt").read(),
        #     'temperature': 0,
        #     'query_prefix': '# ',
        #     'query_suffix': '.',
        #     'stop': ['#', 'object_positions = {'],
        #     'maintain_session': False,
        #     'debug_mode': False,
        #     'include_context': True,
        #     'has_return': True,
        #     'return_val_name': 'judge',
        # },
        # 'VLM': {
        #     'prompt_text': '',
        #     'temperature': 0.7,
        #     'query_prefix': '# ',
        #     'query_suffix': '.',
        #     'maintain_session': True,
        #     'debug_mode': False,
        #     'has_return': True,
        #     'return_val_name': 'judge',
        # },
    }
}